"""Generate the simplified serial MJCF from the official linkage MJCF + identified parameters.

Bodies G (gimbal), L (proximal), D (distal) keep their CAD frames, so their visual meshes and inertials are copied
verbatim from robot.xml. Rods, horns, the crank P and the coupling link are dropped; pip is coupled to mcp with a
MuJoCo <equality><joint polycoef=.../> (4th-order polynomial).
"""
from __future__ import annotations

import os
import xml.etree.ElementTree as ET
from pathlib import Path

import mujoco
import numpy as np

from .linkage import LinkageHand
from .mathutil import fmt, quat_to_mat, relative_pose

OBJ = mujoco.mjtObj


def _f(v, nd=6):
    return " ".join(f"{x:.{nd}g}" for x in np.asarray(v, float).ravel())


def _body_element(robot_root: ET.Element, name: str) -> ET.Element:
    for b in robot_root.iter("body"):
        if b.get("name") == name:
            return b
    raise KeyError(name)


def _copy_children(src: ET.Element, dst: ET.Element, tags=("inertial", "geom"), used_meshes=None, used_materials=None):
    for child in src:
        if child.tag in tags:
            el = ET.SubElement(dst, child.tag, dict(child.attrib))
            if child.tag == "geom":
                if used_meshes is not None and "mesh" in el.attrib:
                    used_meshes.add(el.attrib["mesh"])
                if used_materials is not None and "material" in el.attrib:
                    used_materials.add(el.attrib["material"])


def build_serial_mjcf(H: LinkageHand, fits_by_finger: dict, out_dir: Path, model_name: str,
                      range_margin_deg: float = 1.0) -> tuple[Path, Path]:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    robot_root = ET.parse(H.robot_xml).getroot()
    scene_root = ET.parse(H.scene_xml).getroot()
    assets_dir = H.robot_xml.parent / robot_root.find("compiler").get("meshdir", "assets")
    meshdir = os.path.relpath(assets_dir, out_dir)

    root = ET.Element("mujoco", model=model_name)
    root.append(ET.Comment(" Generated by ah_serial.build_mjcf from the official AmazingHand MJCF: "
                           "serial simplification palm -> abd -> mcp -> pip per finger, pip coupled to mcp "))
    ET.SubElement(root, "compiler", angle="radian", meshdir=meshdir, autolimits="true")
    default = ET.SubElement(root, "default")
    mjcf = ET.SubElement(default, "default", {"class": "mjcf"})
    ET.SubElement(mjcf, "joint", frictionloss="0.1", armature="0.005")
    ET.SubElement(mjcf, "position", kp="50", dampratio="1")
    vis = ET.SubElement(mjcf, "default", {"class": "visual"})
    ET.SubElement(vis, "geom", type="mesh", contype="0", conaffinity="0", group="2")
    col = ET.SubElement(mjcf, "default", {"class": "collision"})
    ET.SubElement(col, "geom", group="3")
    ser = ET.SubElement(default, "default", {"class": "serial_joint"})
    ET.SubElement(ser, "joint", type="hinge", damping="0.02", frictionloss="0.0", armature="0.0005")
    ET.SubElement(default, "equality", solref="0.002 1", solimp="0.99 0.999 0.0005 0.5 2")

    asset = ET.SubElement(root, "asset")
    used_meshes, used_materials = set(), set()

    world = ET.SubElement(root, "worldbody")
    palm_src = _body_element(robot_root, H.palm_name)
    palm = ET.SubElement(world, "body", name=H.palm_name, pos=palm_src.get("pos", "0 0 0"),
                         quat=palm_src.get("quat", "1 0 0 0"), childclass="mjcf")
    _copy_children(palm_src, palm, ("inertial", "geom"), used_meshes, used_materials)

    equality = ET.SubElement(root, "equality")
    actuator = ET.SubElement(root, "actuator")
    key_qpos = []
    m = H.model
    name_of = lambda b: mujoco.mj_id2name(m, OBJ.mjOBJ_BODY, b)  # noqa: E731
    rng = np.radians(range_margin_deg)

    for f, g in zip(H.fingers, H.geometry):
        fits = fits_by_finger[f.n]
        jr = fits["joint_ranges_rad"]
        n = f.n
        RG, RL, RD = (quat_to_mat(getattr(g, k + "_quat")) for k in "GLD")
        L_pos, L_quat = relative_pose(g.G_pos, RG, g.L_pos, RL)
        D_pos, D_quat = relative_pose(g.L_pos, RL, g.D_pos, RD)

        gim = ET.SubElement(palm, "body", name=f"f{n}_gimbal", pos=_f(g.G_pos), quat=_f(g.G_quat))
        ET.SubElement(gim, "joint", {"name": f"f{n}_abd", "class": "serial_joint", "pos": _f(g.abd_jpos),
                                     "axis": _f(g.abd_axis), "range": _f([jr["abd"][0] - rng, jr["abd"][1] + rng])})
        _copy_children(_body_element(robot_root, name_of(f.G)), gim, ("inertial", "geom"), used_meshes, used_materials)

        prox = ET.SubElement(gim, "body", name=f"f{n}_proximal", pos=_f(L_pos), quat=_f(L_quat))
        ET.SubElement(prox, "joint", {"name": f"f{n}_mcp", "class": "serial_joint", "pos": _f(g.mcp_jpos),
                                      "axis": _f(g.mcp_axis), "range": _f([jr["mcp"][0] - rng, jr["mcp"][1] + rng])})
        _copy_children(_body_element(robot_root, name_of(f.L)), prox, ("inertial", "geom"), used_meshes, used_materials)

        dist = ET.SubElement(prox, "body", name=f"f{n}_distal", pos=_f(D_pos), quat=_f(D_quat))
        ET.SubElement(dist, "joint", {"name": f"f{n}_pip", "class": "serial_joint", "pos": _f(g.pip_jpos),
                                      "axis": _f(g.pip_axis), "range": _f([jr["pip"][0] - 3 * rng, jr["pip"][1] + 3 * rng])})
        _copy_children(_body_element(robot_root, name_of(f.D)), dist, ("inertial", "geom"), used_meshes, used_materials)
        ET.SubElement(dist, "site", name=f"tip{n}", group="3", pos=_f(g.tip_pos), quat=_f(g.tip_quat))

        coef = list(fits["coupling_pip_of_mcp"]["coef_ascending"]) + [0.0] * 5
        ET.SubElement(equality, "joint", name=f"f{n}_pip_coupling", joint1=f"f{n}_pip", joint2=f"f{n}_mcp",
                      polycoef=_f(coef[:5], 8))
        for jn in ("abd", "mcp"):
            ET.SubElement(actuator, "position", {"name": f"f{n}_{jn}", "joint": f"f{n}_{jn}", "class": "mjcf",
                                                 "ctrlrange": _f([jr[jn][0], jr[jn][1]])})
        key_qpos += [0.0, 0.0, 0.0]

    # assets actually used
    for mesh in robot_root.find("asset").findall("mesh"):
        stem = mesh.get("name") or Path(mesh.get("file")).stem
        if stem in used_meshes:
            ET.SubElement(asset, "mesh", name=stem, file=mesh.get("file"))
    for mat in robot_root.find("asset").findall("material"):
        if mat.get("name") in used_materials:
            ET.SubElement(asset, "material", dict(mat.attrib))

    key = ET.SubElement(root, "keyframe")
    ET.SubElement(key, "key", name="zero", qpos=_f(key_qpos))

    ET.indent(root, space="  ")
    model_path = out_dir / "serial_hand.xml"
    ET.ElementTree(root).write(model_path, encoding="unicode", xml_declaration=True)

    # scene: reuse the official scene (floor, lights, mocap fingertip targets), include our model instead
    for inc in list(scene_root.findall("include")):
        if inc.get("file") == "robot.xml":
            inc.set("file", "serial_hand.xml")
        elif inc.get("file") == "keyframes.xml":
            scene_root.remove(inc)
    scene_root.set("model", model_name + "_scene")
    ET.indent(scene_root, space="  ")
    scene_path = out_dir / "scene.xml"
    ET.ElementTree(scene_root).write(scene_path, encoding="unicode", xml_declaration=True)
    return model_path, scene_path
